{ config, pkgs, lib, ... }:

let
  # Generated by nix-flatpak
  statePath = "/nix/var/nix/gcroots/flatpak-state.json";

  newPackagesBash = toString (map (s: lib.strings.escapeShellArg s.appId)
    config.services.flatpak.packages);
  newPackagesJson = builtins.concatStringsSep ","
    (map (s: ''"'' + s.appId + ''"'') config.services.flatpak.packages);

  # Prevent flatpak from autopruning manually-installed runtimes by adding them to flatpak-pin,
  # and remove pins for packages that are no longer manually installed.
  # This only prevents flatpak from automatically removing them: it does not
  # pin their versions.
  # Note that `flatpak pin` is currently unnecessary for non-runtime packages,
  # but it doesn't cause any harm to add them in as a side-effect either.
  updateFlatpakPins = pkgs.writeShellScript "update-flatpak-pins" ''
    set -euo pipefail

    if [ -f '${statePath}' ]; then
      OLD_STATE=$(${pkgs.coreutils}/bin/cat '${statePath}')
    else
      OLD_STATE={}
    fi

    # Add package pins
    for appid in ${newPackagesBash}; do
      ${pkgs.flatpak}/bin/flatpak pin "$appid"
    done

    # Remove pins for packages that are in OLD_STATE but not in the new state
    ${pkgs.jq}/bin/jq -r -n \
      --argjson old "$OLD_STATE" \
      --argjson new '{"packages":[${newPackagesJson}]}' \
      '(($old.packages // []) - ($new.packages // []))[]' \
      | while read -r appid; do
        ${pkgs.flatpak}/bin/flatpak pin --remove "$appid"
      done
  '';
in {
  services.flatpak.enable = true;

  # nix-flatpak runs 'flatpak install' with --no-auto-pin, so this is necessary
  systemd.services.update-flatpak-pins = {
    # Run before flatpak-managed-install so that we can access the old state
    wantedBy = [ "flatpak-managed-install.service" ];
    before = [ "flatpak-managed-install.service" ];

    serviceConfig = {
      Type = "oneshot";
      ExecStart = updateFlatpakPins;
    };
  };
}
