# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # TODO: flat subvolume structure
  fileSystems."/" =
    { device = "/dev/mapper/cryptroot";
      fsType = "btrfs";
      # user_subvol_rm_allowed=on allows using btrfs subvolume delete by non root
      # This is safe because rm can already do this
      options = [ "subvol=@" "compress-force=zstd:5" "noatime" "user_subvol_rm_allowed" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/deb2d889-7ae8-42be-986f-3105a0e8c96a";

  fileSystems."/mnt/hard_drive" =
    { device = "/dev/mapper/crypthdd";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypthdd".device = "/dev/disk/by-uuid/368d0031-073f-421c-bd46-bbee0dabdc98";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/41AE-B633";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
